 const  defaultData = [
{ name: "Ana", lastName: "González", age: 28, status: "Active" },
  { name: "Luis", lastName: "Martínez", age: 34, status: "Inactive" },
  { name: "Carlos", lastName: "Soto", age: 41, status: "Active" },
  { name: "María", lastName: "Pérez", age: 25, status: "Active" },
  { name: "Jorge", lastName: "Ramírez", age: 37, status: "Inactive" },
  { name: "Camila", lastName: "López", age: 31, status: "Active" },
  { name: "Pedro", lastName: "Torres", age: 29, status: "Active" },
  { name: "Valentina", lastName: "Castro", age: 22, status: "Inactive" },
  { name: "Diego", lastName: "Reyes", age: 45, status: "Active" },
  { name: "Fernanda", lastName: "Silva", age: 33, status: "Inactive" },
  { name: "Ignacio", lastName: "Herrera", age: 26, status: "Active" },
  { name: "Laura", lastName: "Morales", age: 39, status: "Active" },
  { name: "Sebastián", lastName: "Rojas", age: 30, status: "Inactive" },
  { name: "Daniela", lastName: "Fuentes", age: 27, status: "Active" },
  { name: "Tomás", lastName: "Navarro", age: 36, status: "Inactive" },
  { name: "Josefina", lastName: "Cortés", age: 32, status: "Active" },
  { name: "Matías", lastName: "Vargas", age: 24, status: "Active" },
  { name: "Antonia", lastName: "Campos", age: 38, status: "Inactive" },
  { name: "Gabriel", lastName: "Muñoz", age: 40, status: "Active" },
  { name: "Isidora", lastName: "Pizarro", age: 35, status: "Inactive" },
  { name: "Sofía", lastName: "Ortiz", age: 26, status: "Active" },
  { name: "Andrés", lastName: "Vega", age: 32, status: "Inactive" },
  { name: "Elena", lastName: "Moreno", age: 28, status: "Active" },
  { name: "Ricardo", lastName: "Delgado", age: 45, status: "Inactive" },
  { name: "Natalia", lastName: "Cabrera", age: 24, status: "Active" },
  { name: "Esteban", lastName: "Soto", age: 38, status: "Inactive" },
  { name: "Claudia", lastName: "Ramos", age: 33, status: "Active" },
  { name: "Mauricio", lastName: "Cortés", age: 40, status: "Inactive" },
  { name: "Bárbara", lastName: "Araya", age: 29, status: "Active" },
  { name: "Pablo", lastName: "Menéndez", age: 37, status: "Inactive" },
  { name: "Romina", lastName: "Salazar", age: 30, status: "Active" },
  { name: "Fabián", lastName: "Riquelme", age: 42, status: "Active" },
  { name: "Patricia", lastName: "Zúñiga", age: 31, status: "Inactive" },
  { name: "Cristóbal", lastName: "Godoy", age: 35, status: "Active" },
  { name: "Martina", lastName: "Lagos", age: 23, status: "Inactive" },
  { name: "Benjamín", lastName: "Carrasco", age: 27, status: "Active" },
  { name: "Paula", lastName: "Henríquez", age: 36, status: "Inactive" },
  { name: "Álvaro", lastName: "Espinoza", age: 39, status: "Active" },
  { name: "Javiera", lastName: "Saavedra", age: 28, status: "Inactive" },
  { name: "Rodrigo", lastName: "Tapia", age: 34, status: "Active" }

];


export default defaultData;